clear;
close all;

load('imdb-seed-1.mat');
load('result-dsift.mat');

baseTestIndices = [...
  find(not(cellfun('isempty', strfind(images.name(1:660), 'Acinetobacter.baumanii_0005')))), ...
  find(not(cellfun('isempty', strfind(images.name(1:660), 'Actinomyces.israeli_0011')))), ...
  find(not(cellfun('isempty', strfind(images.name(1:660), 'Bacteroides.fragilis_0005')))), ...
  find(not(cellfun('isempty', strfind(images.name(1:660), 'Bifidobacterium.spp_0019')))), ...
  find(not(cellfun('isempty', strfind(images.name(1:660), 'Candida.albicans_0001')))), ...
  find(not(cellfun('isempty', strfind(images.name(1:660), 'Clostridium.perfringens_0007')))), ...
  find(not(cellfun('isempty', strfind(images.name(1:660), 'Enterococcus.faecalis_0003')))), ...
  find(not(cellfun('isempty', strfind(images.name(1:660), 'Enterococcus.faecium_0012')))), ...
  find(not(cellfun('isempty', strfind(images.name(1:660), 'Escherichia.coli_0016')))), ...
  find(not(cellfun('isempty', strfind(images.name(1:660), 'Fusobacterium_0001')))), ...
  find(not(cellfun('isempty', strfind(images.name(1:660), 'Lactobacillus.casei_0007')))), ...
  find(not(cellfun('isempty', strfind(images.name(1:660), 'Lactobacillus.crispatus_0001')))), ...
  find(not(cellfun('isempty', strfind(images.name(1:660), 'Lactobacillus.delbrueckii_0005')))), ...
  find(not(cellfun('isempty', strfind(images.name(1:660), 'Lactobacillus.gasseri_0003')))), ...
  find(not(cellfun('isempty', strfind(images.name(1:660), 'Lactobacillus.jehnsenii_0012')))), ...
  find(not(cellfun('isempty', strfind(images.name(1:660), 'Lactobacillus.johnsonii_0020')))), ...
  find(not(cellfun('isempty', strfind(images.name(1:660), 'Lactobacillus.paracasei_0018')))), ...
  find(not(cellfun('isempty', strfind(images.name(1:660), 'Lactobacillus.plantarum_0013')))), ...
  find(not(cellfun('isempty', strfind(images.name(1:660), 'Lactobacillus.reuteri_0014')))), ...
  find(not(cellfun('isempty', strfind(images.name(1:660), 'Lactobacillus.rhamnosus_0009')))), ...
  find(not(cellfun('isempty', strfind(images.name(1:660), 'Lactobacillus.salivarius_0014')))), ...
  find(not(cellfun('isempty', strfind(images.name(1:660), 'Listeria.monocytogenes_0013')))), ...
  find(not(cellfun('isempty', strfind(images.name(1:660), 'Micrococcus.spp_0005')))), ...
  find(not(cellfun('isempty', strfind(images.name(1:660), 'Neisseria.gonorrhoeae_0010')))), ...
  find(not(cellfun('isempty', strfind(images.name(1:660), 'Porfyromonas.gingivalis_0011')))), ...
  find(not(cellfun('isempty', strfind(images.name(1:660), 'Propionibacterium.acnes_0014')))), ...
  find(not(cellfun('isempty', strfind(images.name(1:660), 'Proteus_0009')))), ...
  find(not(cellfun('isempty', strfind(images.name(1:660), 'Pseudomonas.aeruginosa_0011')))), ...
  find(not(cellfun('isempty', strfind(images.name(1:660), 'Staphylococcus.aureus_0018')))), ...
  find(not(cellfun('isempty', strfind(images.name(1:660), 'Staphylococcus.epidermidis_0017')))), ...
  find(not(cellfun('isempty', strfind(images.name(1:660), 'Staphylococcus.saprophiticus_0020')))), ...
  find(not(cellfun('isempty', strfind(images.name(1:660), 'Streptococcus.agalactiae_0016')))), ...
  find(not(cellfun('isempty', strfind(images.name(1:660), 'Veionella_0010')))), ...
];

for i=1:numel(baseTestIndices)
  baseTestIndex = baseTestIndices(i);
  testIndices = find(segments.baseImageId == baseTestIndex);
  testIndices = testIndices(2:end);

  label = segments.label(baseTestIndex);
  if ismac
    dataDir = '../../BigData/bacteria/';
  else
    dataDir = '/media/bz/C4048A7D048A71EA/BigData/bacteria/';
  end
  im = imread([dataDir, 'data/bacteria/', images.name{baseTestIndex}]);
  bigMask = segments.bigMask{baseTestIndex};
  noSuperpixels = max(bigMask(:));

  X = zeros(noSuperpixels, numel(testIndices));
  index = 0;
  for testIndex=testIndices
    index = index + 1;
    X(:, index) = segments.mask{testIndex}.smallMask;
  end

  y = scores(label, testIndices);
  %y = y == max(scores(:, testIndices));

  %%

  if 0
    [B, FitInfo] = lasso(X', y);
    lassoPlot(B, FitInfo);

    for b=size(B, 2):-1:1
      mask = zeros(size(bigMask));
      mm = find(B(:, b) ~= 0);
      for m=mm'
        mask(bigMask == m) = 1;
      end

      tempIm = im;
      tempIm(~mask) = 0;
      imshow(tempIm);
      pause;
    end
  end

  %%

  ens = fitensemble(X', y,'LSBoost', 10, 'Tree');
  imp = predictorImportance(ens);
  [sImp, oImp] = sort(imp, 'descend');

  mask = zeros(size(bigMask));
  for m=1:length(oImp)
    mask(bigMask == oImp(m)) = uint8(256 * sImp(m) / max(sImp));
  end

  tempIm = im;
  tempIm(:, :, 3) = mask;
  %subplottight(5, 7, i);
  imshow(tempIm);

  pause;
end
